/*
 * 002_LED_Button.c
 *
 *  Created on: Nov 11, 2024
 *      Author: solom
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <memory.h>
#include "stm32f767xx_gpio_driver.h"
#include "stm32f767xx.h"

#define LOW DISABLE


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void)
{
	for(uint32_t i =0; i<500000/5 ; i++);
}

int main(void)
{
	GPIO_Handle_t GpioLed, GpioButton;

	memset(&GpioLed,0,sizeof(GpioLed));
	memset(&GpioButton,0,sizeof(GpioButton));

	GpioLed.pGPIOx =GPIOB;

	GpioButton.pGPIOx = GPIOC;

	/* LED config */

	GpioLed.GPIOPinConfig.GPIO_PinNumber = GPIO_PIN_7;

	GpioLed.GPIOPinConfig.GPIO_PinMode = GPIO_MODE_OUT;

	GpioLed.GPIOPinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;

	GpioLed.GPIOPinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

	GpioLed.GPIOPinConfig.GPIO_PinPuPdControl  = GPIO_NO_PP;

	/* Button config */

	GpioButton.GPIOPinConfig.GPIO_PinNumber = GPIO_PIN_13;

	GpioButton.GPIOPinConfig.GPIO_PinMode = GPIO_MODE_IT_RT;

	GpioButton.GPIOPinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;

	//GpioButton.GPIOPinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

	GpioButton.GPIOPinConfig.GPIO_PinPuPdControl  = GPIO_NO_PP;

	GPIO_PeriClkControl(GPIOB, ENABLE);

	GPIO_PeriClkControl(GPIOC, ENABLE);

	SYSCFG_PeriClkControl(ENABLE);

	GPIO_Init(&GpioLed);

	GPIO_Init(&GpioButton);

	/* IRQ handling */
	GPIO_IRQConfig(IRQ_NO_EXTI15_10, IRQ_PRIO_14, ENABLE);

	while(1);


}

void EXTI15_10_IRQHandler (void)
{
	delay();
	GPIO_IRQHandling(GPIO_PIN_13);
	GPIO_ToggleOutputPin(GPIOB, GPIO_PIN_7);
}
